"""Additional Luma seeds discovered AFTER the initial seed list was finalized.
Used by a follow-up merge pass to expand the dataset without re-crawling everything.
"""

# 20 calendar api_ids harvested from the lu.ma/sf page __NEXT_DATA__
# (these are calendars that publish to the SF discover surface)
SF_PAGE_CAL_IDS = [
    "cal-4TEeXLXVUtUqg91", "cal-5thnx2ZyREuxdJz", "cal-752i9ECdyr36HjD",
    "cal-7Q5A70Bz5Idxopu", "cal-GxGNsMwfrZt4srK", "cal-HImlOWziQ7yD36i",
    "cal-JDvWKGO7IFEV3WY", "cal-Q0U4JABvmidBDV4", "cal-QKhanAN5iCONZzq",
    "cal-V1ReDPXTb8z9zcK", "cal-Z1tslEBMjjCh4fd", "cal-abA0XUA5nOEMIvJ",
    "cal-iHkz5obZdong4ta", "cal-kmclvwZFldKtmzj", "cal-nGfPsblC0xslMQD",
    "cal-oOBz9Y16qzmpxg2", "cal-twiOosdGMMY66DI", "cal-veSMzkkl0ywVlWb",
    "cal-yP17DTziybSxLII", "cal-zauF7Gj3RTECxwR",
]

# Slugs discovered via gh search (`gh search code 'lu.ma'`)
GITHUB_DISCOVERED_SLUGS = [
    # AI / SF community calendars
    "aisf", "aisf-hack", "oss-ai", "openclaw",
    "dtc-events", "mlflow", "aidevfeb", "geminimeetup",
    # Other communities (may not be Bay Area; bbox filter handles it)
    "PMHive", "craft_", "scaledown", "the-space-events",
    "events-by-vara-gear", "moment", "mafia", "scala",
    # Slugs from SF page __NEXT_DATA__ that we didn't try
    "AsianHeritageWeek26", "batf", "berkeleygatewayaccelerator",
    "deepmind", "duckdb-motherduck-sfbay", "fdotinc",
    "marinarunclub", "notion-for-startups", "surreal_",
    "thirdlayer", "tiat", "unboundevents",
]

# Slugs from Agent 1 (AI / ML / agents — high-signal named calendars first)
AGENT1_DISCOVERED_SLUGS = [
    # Named AI/ML/agent community calendars (highest signal)
    "ai", "aiengineering", "ai-agents-2", "ai-agents-hackathon",
    "ai-agents-workshop", "ai-builders-and-learners", "ai-for-good",
    "ai-for-good-hackathon", "ai-force", "ai-meetup", "ai-workshop",
    "ai-event", "ai-summit-2024", "ai-agents-summit-2025", "ai-ml-summit",
    "ai-devtools-night", "ai-native-developers-io-week", "ai-search-hack",
    "agents-hackathon-googleai", "agentsday",
    "agentic-ai-summit-livestream", "agihouse", "agivllm", "aimakerspace",
    "aisc-journal-club", "aisc-llm-school", "AI-designer",
    "AI-security-hackathon", "AgentX-Auth0", "AgentX-lambda",
    "berkeley-llm-meetup", "first-vllm-meetup", "vllm-ollama", "ollama",
    "osaurus", "llm-paper-club", "paperclub3", "stateful-agents",
    "swarms_calendar", "haystack", "baml", "baish", "gptfinetuning",
    "GPTuesdays", "gptutor", "geminimeetup", "gemma-unsloth", "mlflow",
    "mlops-community-london", "mlops-now-nov", "chicago-mlops",
    "london-mlops", "capetown-mlops", "practicalml", "MLinParis", "PINSAI",
    "genai-collective", "genai-sf", "sfdata", "sfbenbites", "sync-sf",
    "startup-grind-sf", "thecomputecollective", "dataforai", "DesignandCode",
    "oss-ai", "oss4ai", "intuitoss", "airstreet", "demo-night", "bensbites",
    "actuate", "modular-aug-meetup", "modular-hack-weekend", "modular-meetup",
    "weavehacks3", "flowgpt", "paipalooza", "latent-space-final-frontiers",
    "ls", "stanfordgreenai", "CS224G", "frontierfitnesscenter",
    "githubforstartups", "MongoDB-GenAI-NYC", "SFAIHackathon_MDB",
    "nebius-build-sf-mar15-2026", "nearhacks-sf", "holidayaisocial",
    "lorong-ai", "soai", "tech-bloom-ai-intro", "tech-leaders-dinner",
    "cofounder-speed-dating", "FounderBasecamp", "StartupValley", "polyverse",
    "NobelFutureTech", "RIVAL", "HDSummerCamp2026", "trends2025", "dwr2025",
    "kpai", "lamatic", "thehunt", "regenlearnings", "infer", "encrypt", "claw",
    "hh-ai-hackathon-brown-4-2024", "llm-hackathon-fixie-september-2023",
    "creative-ai-hackathon", "rps-hackathon", "veed-hackathon-2025",
    "roboticshack", "ai-tinkerers-ottawa", "core-coffee", "build-and-sell",
    "sdx-demo-day", "vibecode2", "codecollective", "noderunner",
    "replitdevdaylivestream",
]

# Slugs from Agent 2 (SF Bay Area focused — named SF/Bay slugs highest priority)
AGENT2_DISCOVERED_SLUGS = [
    # Named Bay Area community calendars (highest signal)
    "sf", "sfbayea", "sfruby", "genai-sf", "svgenai", "localthirst-sf",
    "yc-alumni-sf", "yc-aifter-party", "yc-blr-mixer", "ai-tinkerers",
    "ai-tinkerers-sf-feb", "bay-area-safety-unconf", "bayareafoundersclub",
    "berkeley-llm-meetup", "ethereum-10y-sanfrancisco", "STEPSF24-SUNSET",
    "aisf-hack", "0930-ai-in-motion-hack", "hacknight-sanjose-03-18-2025",
    "building-frontier-ai-products", "interfaces-software-spc",
    "southparkcommons-events", "hack-night-wordware-feb19-2026",
    "DevOps-for-GenAI-SF", "SFAIHackathon_MDB", "MongoDB-GenAI-SF",
    "DemoNightEdition2", "AI-demo-jam", "ai-demo-days", "ai-dinner-feb-2026",
    "nyc-ai", "vancouver-ai", "london-ai", "SeattleAIWeek",
    "modular-aug-meetup", "modular-hack-weekend", "modular-meetup",
    "modular-gpu-workshop", "shipdemoday", "aotfdemoday",
    "ai-tinkerers-ottawa", "core-coffee", "build-and-sell",
    "agents-hackathon-intel", "agivllm", "ai-native-developers-io-week",
    "ai-builders", "aimakerspace", "agihouse", "baml", "baish-agisf-w7",
    "first-vllm-meetup", "vllm-ollama", "ollama", "stanfordgreenai",
    "tech-leaders-dinner", "tlvcommunity", "techwalk", "cesv2024",
    "saaspasseconf25", "consensusdays23", "icpcc", "msbc2026-hackathon",
    "ContextCon", "contextcon",
    "MetaEra", "NeXidea", "ODHacks", "PortlandStartupEvents",
    "RustaceansKenya", "Safe_Harbor", "StartupValley", "WaterlooEvents",
    "Waterloo_ca", "waterloo_ca", "waterlooevents", "FounderBasecamp",
    "HDSummerCamp2026", "PINSAI", "Aiifyio", "aiifyio",
    "CopilotDayDelhi", "DICE2025", "DICEecosystems",
    "PitchNightMelb", "BlockMeetTBW", "ACX-London-Oct-2023",
    "ACX-London-Sep-2025", "JTA", "MEV", "AustinRoadshow",
    "Beta-Cohort-Incubator-1", "BASS25",
    "SuperteamGermany", "SolanaXMetacamp", "NEAR_Token2049_SG",
    "MCJLondon_Patch_BeZero_CarbonM", "STMS-03282025-Qin-Zajac",
    "SCMAY", "AITechShowcase",
    "agent", "actuate", "agentic-ai-summit-livestream",
    "bensbites", "buildstation", "build-station-berlin",
    "blktechconnect", "ai-builders-and-learners",
    "claw", "compute", "constitution", "createthefuture", "datingmonday",
    "day-zero-builder-night", "edgeAGI", "experiences",
    "explyra-unveiled", "forbes", "frontierfitnesscenter",
    "fil-sxsw", "govai-social-2", "hackbay",
    "haskell", "helia", "hstcommons_communityevents",
    "ipfscamp22", "ivsaibuildathon", "junglelove",
    "jsconf-india-online-preevent-m", "kugchennai",
    "la-saas-founders-feb2026", "latent-space-final-frontiers",
    "launchNL", "lennysfireside-DJ", "libp2pday-denver",
    "life_upgrade_hackathon", "llamalounge19", "lottiekr_supabase_23",
    "march23", "mcpconference", "mitai2025",
    "monasheesdinner", "motherduck-databricks-dais-202",
    "nytw-aidemoday", "nixos", "novus", "novus28",
    "omscs", "opservations", "optimystics",
    "paqqi50m", "pre-yc-bangalore",
    "randomness-summit-tokyo", "readingrhythms-global",
    "refidao", "regen-lisboa-map",
    "rust-india-2026", "sdx-demo-day", "sefnuj7k",
    "shenzhen-researcher-house", "solana-hh-nyc-2024", "solana-nyc",
    "sphagprs", "startupnetworking", "strange-people",
    "superteam", "superteammy-defi-workshop",
    "superteammy-demoday-q2-2026", "superteammy-hackerhouse-kl-202",
    "superteammy-jan2026", "superteammy-penang-mar2026",
    "superteammy-rust-bootcamp", "techgnosis", "thenetwork",
    "token2049", "tondevdemotw", "vienna-tech-soiree",
    "wbcs4l69", "web3holidaydrive23", "web3reinvent",
    "westcoastlakehouse", "xrpl_builders_bootcamp",
    "zknyc01",
]

AGENT3_DISCOVERED_SLUGS = [
    "555mtl", "AI-designer", "ai-playbook", "arweave-day-ind", "baml",
    "beyondcuda25", "civic-tech-dc", "core-coffee", "figma-for-kw",
    "foclondon", "localgovdrupal", "londoncss-6", "paipalooza",
    "philaconvalley", "yakcon", "CryptoKitchen-ZKday", "accelerate-miami",
    "alts", "chicago-mlops", "crypto", "crypto-ai-symposium", "crypto-defi",
    "crypto_cities", "cryptobuildersba", "cryptocanal", "cryptocarnival-ncr",
    "cryptolar", "cryptosummit", "encrypt", "ethbelgium", "infrabrunch",
    "osaurus", "pgpforcrypto20250325", "roboticshack", "rust-girona",
    "swarms_calendar", "Team1", "aiblockchainnyc", "bassdenver",
    "berkeley_blockchain_innovation", "blockchain-and-beers", "depin-berlin",
    "developer-education-program", "ftc-berlin-2025", "psoc-blockchain-workshop",
    "urbitBBW", "urbitprague", "zama-meetup-barcelona-blockcha",
    "AIPowered", "Solana-TBW2024", "SolanaXMetacamp", "SolanaxBITSMesraS2",
    "TRGC-Infracon-AI", "austin-hacker-house", "barcelona-hacker-house",
    "bengaluru-hh-2024", "bogota-hacker-house", "build-station-berlin",
    "dubai-hh-2024", "hk-hacker-house", "krakow-hacker-house",
    "lisbon-hacker-house", "london-hacker-house", "london-hh-2024",
    "paris-hacker-house", "prague-hacker-house", "singapore-hh", "solana",
    "solana-hh-nyc-2024", "solana-nyc", "solana-summit-apac-2025",
    "solanaANZ", "solanabanksimulator", "solanaecodubai",
    "solanafoundation-community", "solanahackerhouse", "solanarunclub",
    "solanaspeed", "solanathonkickoff", "superteam", "Mondaytechweek",
    "VAN-Demo-Day", "aikidosecurity", "bitsinbio", "chicagotech",
    "customer-agent", "flh-noida", "hw-nytech-6-3-24", "lovehack",
    "nyc-ai-breakfast-feb2026", "nytw-comedy-night", "sf-founder-meetup",
    "stacks-latam", "websummit-vancouver", "AIBOM-workshop-RSAC2024",
    "PINSAI", "SparksXGenesis", "UnrestrictedIntelligence", "ai-agents-2",
    "ai-agents-hackathon", "ai-agents-workshop", "ai-builders-and-learners",
    "ai-builders-london", "ai-for-good", "ai-force", "ai-leaders-blr",
    "ai-meetup", "ai-workshop", "aiengineering", "airstreet",
    "aisalon-phoenix-may2024", "aisc-journal-club", "aixclimate",
    "cto-summit-blr", "dataforai", "demo-night", "githubforstartups",
    "ldn_software_guild", "libp2p", "londonlivecoding", "londonmaxxing-ai",
    "mlops-community-london", "oss-ai", "public-ai-dinner-party-neurips",
    "stanfordgreenai", "tech-leaders-dinner", "tmc-london-meetup-nov2024",
    "AI-security-hackathon", "Encode-London-25", "LondonVibeCodingMasterclass",
    "ManchesterVibeCodingMasterclas", "MongoDB-GenAI-NYC", "WLH-connect-05",
    "agihouse", "ai-search-hack", "avalanchesummitlondonhackathon",
    "berlin-hackathon", "build-and-sell", "creative-ai-hackathon",
    "edth-2025-berlin", "edth-2025-london", "edth-2025-milan",
    "edth-2025-munich", "edth-2025-switzerland", "flowgpt",
    "hackathon-latam", "hackathon-zurich-26270925",
    "hacking-agents-hackathon-londo", "hh-ai-hackathon-brown-4-2024",
    "munich-hack", "nebius-build-sf-mar15-2026", "paris-hackathon",
    "rp3gamecodealong", "rp3kickoff", "rp3submissions", "rps-hackathon",
    "solresol", "sui-bkk-hh-2024", "swissai-lausanne", "tech-munich",
    "veed-hackathon-2025", "vibecode2", "ai-devtools-night",
    "astro-together-meetup-2024", "civictechwr", "devtools2", "devtools3",
    "halfbakedhackathon", "ipfs", "mcpdevsummit2025", "sweat-token2049",
    "sync-ghent", "vandevirl2", "StarknetConnect_Hyd2", "bhopaldao",
    "d-d-push-protocol-workshop", "dao-night3", "daospring", "descisummit",
    "developer-dao-events", "kahluafl", "moondao", "refidao", "safe_harbor",
    "stockholm-hacker-house", "threefoldherdao", "PortlandStartupEvents",
    "boulder-ruby", "boulder-tech-connect", "first-vllm-meetup",
    "geminimeetup", "llm-meetup-tokyo-1", "rsa-sbom-meetup",
    "vibe-coding", "BasedBerlin24", "CopilotDayDelhi", "EastCoastLakehouse",
    "Lakehouselinkups", "NYCDataLakehouse", "Orbis86GameOnNYCNYTW24",
    "Orlandodata", "boston", "calimajc2024", "fois_techweek", "insync",
    "la", "nyc-ai", "nyc-inventing-on-principle", "nyc-networking", "nycai",
    "nycbasemeetup", "nyctechweekppf", "nyctnb", "sf", "toronto",
    "vllm-ollama", "westcoastlakehouse", "zknyc01", "adplistcommunity",
    "anthropic", "config2024", "dtc-potw-diypythonpackage", "genai-collective",
    "nearhacks-sf", "sf-ebl", "sf-tech-week", "sfWritingClubCalendar",
    "sfbayea", "sync-sf", "tlvcommunity", "DICEecosystems", "LSEevent",
    "VCDay_Vancouver", "ai-agents-summit-2025", "dtc-potw-dvc1",
    "itl", "trends2025", "vienna-tech-soiree",
]
